<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="F049LTRV" name="com.scripted.runners.WebTestNGRunner" tests="3" failures="3" timestamp="30 Jul 2020 11:50:19 GMT" time="974.727" errors="0">
  <testcase name="runScenario" time="325.093" classname="com.scripted.runners.WebTestNGRunner">
    <failure type="junit.framework.AssertionFailedError" message="Error after trying to heal">
      <![CDATA[junit.framework.AssertionFailedError: Error after trying to heal
at junit.framework.Assert.fail(Assert.java:57)
at com.scripted.web.WebHandlers.initiateHealCall(WebHandlers.java:127)
at com.scripted.web.WebHandlers.click(WebHandlers.java:167)
at com.scripted.CRMPomObjects.CRMContactsPage.clickContacts(CRMContactsPage.java:91)
at com.scripted.selfhealingwebstepdefs.stepdefinitions.i_navigate_to_contact_page(stepdefinitions.java:236)
at ✽.I navigate to contact page(file:Features/SelfHealing/TC001NoSchElmExcptn.feature:33)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="324.745" classname="com.scripted.runners.WebTestNGRunner">
    <failure type="junit.framework.AssertionFailedError" message="Error after trying to heal">
      <![CDATA[junit.framework.AssertionFailedError: Error after trying to heal
at junit.framework.Assert.fail(Assert.java:57)
at com.scripted.web.WebHandlers.initiateHealCall(WebHandlers.java:127)
at com.scripted.web.WebHandlers.click(WebHandlers.java:167)
at com.scripted.CRMPomObjects.CRMContactsPage.clickContacts(CRMContactsPage.java:91)
at com.scripted.selfhealingwebstepdefs.stepdefinitions.i_navigate_to_contact_page(stepdefinitions.java:236)
at ✽.I navigate to contact page(file:Features/SelfHealing/TC001NoSchElmExcptn.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="324.889" classname="com.scripted.runners.WebTestNGRunner">
    <failure type="junit.framework.AssertionFailedError" message="Error after trying to heal">
      <![CDATA[junit.framework.AssertionFailedError: Error after trying to heal
at junit.framework.Assert.fail(Assert.java:57)
at com.scripted.web.WebHandlers.initiateHealCall(WebHandlers.java:127)
at com.scripted.web.WebHandlers.click(WebHandlers.java:167)
at com.scripted.CRMPomObjects.CRMContactsPage.clickContacts(CRMContactsPage.java:91)
at com.scripted.selfhealingwebstepdefs.stepdefinitions.i_navigate_to_contact_page(stepdefinitions.java:236)
at ✽.I navigate to contact page(file:Features/SelfHealing/TC001NoSchElmExcptn.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.scripted.runners.WebTestNGRunner -->
