<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="B701LMAA" name="com.scripted.selfhealing_testscripts.CompleteTest_Self_Healing" tests="2" failures="1" timestamp="11 May 2020 09:32:46 GMT" time="22.457" errors="0">
  <testcase name="TC005_TimeoutCheck" time="22.265" classname="com.scripted.selfhealing_testscripts.CompleteTest_Self_Healing"/>
  <testcase name="teardown" time="0.192" classname="com.scripted.selfhealing_testscripts.CompleteTest_Self_Healing">
    <failure type="java.lang.AssertionError" message="Error occurred while closing browserException :java.lang.NullPointerException">
      <![CDATA[java.lang.AssertionError: Error occurred while closing browserException :java.lang.NullPointerException
at org.testng.Assert.fail(Assert.java:96)
at com.scripted.web.BrowserDriver.closeBrowser(BrowserDriver.java:170)
at com.scripted.selfhealing_testscripts.BaseTest_selfhealing.teardown(BaseTest_selfhealing.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- teardown -->
</testsuite> <!-- com.scripted.selfhealing_testscripts.CompleteTest_Self_Healing -->
